name: First WorkFlow
on: [push]

jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
            - name: Dispaly some text 
              run: echo "Hello, World!"
            - name: Command in Multi-line
              run: |
                node -v 
                npm -v